### ISSUE TITLE
Triple redirect

### ISSUE THREAD

**Issue by niieani** [klevstul/NoCountryRedirect#14]
Since the last week or so, I started experiencing annoying triple redirects whenever I use the search bar.

When typing `test` in the Omnibar, it first loads the URL:

`https://www.google.pl/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8`

Then redirects to:

`https://www.google.com/search?q=test&oq=test&aqs=chrome..69i57j69i60j69i61l2j69i60j0.1277j0j1&sourceid=chrome&ie=UTF-8`

And finally to:

`https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=test`

This didn't used to happen, so I presume Chrome introduced some change which started causing this. I'm on the latest beta, which is Version 55.0.2883.59 beta (64-bit) on macOS.

**Comment by klevstul** [comment]
thanks for your detailed report, @niieani . i will look into this.

**Comment by niieani** [comment]
I've managed to workaround this problem by going to https://google.com/ncr and restarting the Chrome browser. I guess that site sets some special cookie or something, though not sure why this problem started occurring two weeks ago, but that seems to be the workaround.

**Comment by klevstul** [comment]
thanks for the update. weird one, but as you say, it might be caused by some cookies. another workaround is using encrypted.google.com as your default search engine. there is a "how to" under ncr's options page. that prevents any redirects.

**Comment by niieani** [comment]
Yeah, I saw it, but I am using Chrome Beta and its latest version (at the time) had some sort of a bug preventing me from changing the default search engine. 

I guess "going to https://google.com/ncr and restarting the Chrome browser" could be added to the "how to" page as an alternative workaround.

**Comment by klevstul** [comment]
aha. and yes, good suggestion to add info about the workaround you found.

so, these are the simple steps:
1. go to https://google.com/ncr
2. close chrome
3. start chrome
?

**Comment by niieani** [comment]
Yeah, in fact this is the official advice from Google on the [Chrome blog](https://googlesystem.blogspot.com/2013/07/change-chromes-search-engine-to.html).

**Comment by klevstul** [comment]
thanks again, @niieani !

**Comment by klevstul** [comment]
to be deployed with #13
