### ISSUE TITLE
Google Flights redirect to country-specific page

### ISSUE THREAD

**Issue by dottedmag** [klevstul/NoCountryRedirect#2]
https://www.google.com/flights/ redirects to https://www.google.no/flights/ (or whatever the current country Google thinks it is).

**Comment by klevstul** [comment]
thanks for the bug report. i will look into this, and hopefully have a fix ready with next release.

**Comment by klevstul** [comment]
fix has been implemented, and currently being tested. new version will be deployed soon.

**Comment by klevstul** [comment]
new version deployed, and being rolled out to users now.

**Comment by dottedmag** [comment]
Yay, it works!

**Comment by klevstul** [comment]
:+1:

**Comment by dottedmag** [comment]
Hi.

The redirector seems to fail on some pages. Try this one: https://www.google.no/flights/#search;f=OSL;t=MLA;d=2016-05-21;r=2016-05-25;md=540 -- it gets redirected three times and ends up with https://www.google.no/flights/#search;f=OSL;t=MLA;d=2016-05-21;r=2016-05-25;md=540?gl=US?gl=US?gl=US (which accidentally breaks md=540 as well)

**Comment by klevstul** [comment]
hi. thanks for your feedback. i will look into this, as soon as i get some time. cheers, frode.

**Comment by klevstul** [comment]
it seems like i have a fix to this problem. i will test it a bit more, then roll out a new version. once again, thanks for notifying me of this bug.

cheers,
frode.

**Comment by klevstul** [comment]
this has now been fixed, and version 1.2.1602 is being rolled out to all users in this very moment.

cheers,
frode.
