### ISSUE TITLE
OBSOLETE : images.google.[tld] not redirecting

### ISSUE THREAD

**Issue by klevstul** [klevstul/NoCountryRedirect#24]
images.google.[tld], like images.google.no, is not redirecting

**Comment by ZenFi** [comment]
Fixed?

Oh btw I'm testing this ext for Opera :)

**Comment by klevstul** [comment]
@ZenFi not fixed yet. however, if you go do https://images.google.com/ are you automatically redirected? 

cool you're testing it on opera. didn't know it could be used out-of-the-box there.

**Comment by ZenFi** [comment]
Sure, Opera users can install extensions from both Opera extensions site and Chrome web store.
Also Vivaldi is Blink/Chromium based and Vivaldi users as well actually mainly get exts from Chrome's site.

I tried other NCR mod before this yours called "omnibox ncr" - it kind of works in Opera's omnibox and kind of not, tiny bugs there I guess with Opera. Image NCR is working on that...

About blogspot: I saw another ext in Chrome store that was for both blogspot and blogger - aren't those kind of the same? Anyhow..

What would be great if in this type of extension settings one could add redirectors - for example based on custom search engines. Dunno. I'm also bit of studying could encrypted.google.com be used on Google Search. Also adding trackurl remove from search results.

Oh and Yandex is very good for reverse image searches. But perhaps reverse image search is better on another ext.

Gonna test Google Images redirect a little later.

**Comment by ZenFi** [comment]
So far works very very well in Opera - better than NCR Omnibox. 

Images I'll see later..

**Comment by klevstul** [comment]
@ZenFi 
blogger.com is the admin interface for blogspot.com blogs, so yeah, it's the same. blogger.com doesn't get redirected. only blogs hosted as subdomains on blogspot.com.

personally, i do not get redirected when i visit https://images.google.com. it would be nice if you can visit that domain and see if you are redirected or not. maybe this is no bug that needs to be fixed at all.

my goal is to keep ncr quite simple, not adding many extra features. however, i will consider suggestions.

**Comment by ZenFi** [comment]
^ That Google Images link works for me, your NCR kicks in. Could there be some mishap in regular expression in the code?

Hmm. Btw. when I type google.com to the omnibox it goes to google.com front page, and then when I click  "Images" on top-right side of screen Google takes to this address: 
https://www.google.com/imghp?hl=en&tab=wi  

Could there be something you could do?

Also if I search images at https://images.google.com/ Google takes to image results page that starts with https://www.google.com/search?.............

**Comment by klevstul** [comment]
@ZenFi 
thanks a lot for your feedback. i will take a look at it.

**Comment by klevstul** [comment]
**UPDATE**
`images.google.[tld]` domains never redirect, hence this change is not needed. the user can simply enter `images.google.com` and no redirect will be made. same thing if you visit `images.google.no`, you would just stay on that domain.

with this change, you can no longer visit country-specific image search domains without being redirected to images.google.com (unless you whitelist `images.google` that is).

it boils down to the fact that no change will be done.

**noteToSelf**
changes required for the fix:

```
- regExpUrlsToCheck[0]    = new RegExp("^http(s)?://(books.|maps.|scholar.|www.)?google.\\w{2,3}(.\\w{2,3})?/", "i");                         // google domains
+ regExpUrlsToCheck[0]    = new RegExp("^http(s)?://(books.|images.|maps.|scholar.|www.)?google.\\w{2,3}(.\\w{2,3})?/", "i");                         // google domains

- var googleRegExp            = new RegExp("^http(s)?://(books.|maps.|scholar.|www.)?google.\\w{2,3}(.\\w{2,3})?/$", "i");
+ var googleRegExp            = new RegExp("^http(s)?://(books.|images.|maps.|scholar.|www.)?google.\\w{2,3}(.\\w{2,3})?/$", "i");
```

**Comment by klevstul** [comment]
relates #20
