### ISSUE TITLE
google.org shouldn't redirect to google.com

### ISSUE THREAD

**Issue by niieani** [klevstul/NoCountryRedirect#27]
It's not possible to go to this website: https://google.org/crisismap/2017-harvey with NCR, because it redirects to https://google.com/crisismap/2017-harvey which is a 404.

Workaround is to whitelist the google.org domain.

**Comment by klevstul** [comment]
@niieani 
thank you for the bug report!

**Comment by klevstul** [comment]
to be deployed with #20
